services:
  mongodb:
    image: mongo:latest
    container_name: family-blog-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=family-blog

volumes:
  mongodb_data:
